# Generated by Django 2.2.4 on 2019-11-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('uno', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('qualification', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('proof', models.CharField(max_length=30)),
            ],
        ),
    ]
