# Generated by Django 2.2.4 on 2019-11-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helth_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicienandDiseasesModel',
            fields=[
                ('mdno', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('medicines', models.CharField(max_length=30)),
            ],
        ),
    ]
